# Configuring https://pre-commit.ci/
ci:
  autoupdate_schedule: monthly

exclude: "conf.py"

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: docs/source/publications.md # lots of author names
