name: Update Citations

on:
  # Only run on pushes to main, or when version tags are pushed
  push:
    branches:
      - "main"
  # Run on all pull-requests
  pull_request:
  schedule:
    # Runs at 6:10am UTC on Monday
    - cron: '10 6 * * 1'
  # Allow workflow dispatch from GitHub
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r docs/requirements.txt
      - run: python scripts/auto_collect_brainglobe_tools_pub.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update citations list'
          file_pattern: publications.md